version: '3.8'

services:
  teste_api:
    build:
      context: ./ex1
      dockerfile: Dockerfile
    ports:
      - "16000:16000"
    depends_on:
      - mongodb
  teste_client:
    build:
      context: ./ex2
      dockerfile: Dockerfile
    ports:
      - "16001:16001"
    depends_on:
      - teste_api
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed
  mongo-seed:
    image: mongo:latest
    volumes:
      - ./contratos2024.json:/dataset.json
    command: mongoimport --host mongodb -d contratos -c contratos --type json --file dataset.json --jsonArray